### PR TITLE
Show all sub process scopes

### LINKED ISSUE #205: Transaction/Ad-Hoc Subprocesses are not logged/counted
### Describe the Bug

Unlike event and embedded subprocesses, transaction and ad-hoc subprocesses are not logged when a token enters/leaves and their tokens are not available in the show scope toggle bar.

### Steps to Reproduce

1. Open the demo modeler: https://bpmn-io.github.io/bpmn-js-token-simulation/modeler.html
2. Change the sub process to transaction.
3. Trigger the start event.

### Expected Behavior

When a token enters the transaction, a log entry should appear (SubProcess started/Cash Withdrawal started) and the token count should appear at the toggle bar, so we can show only those tokens. When the token leaves the transaction that should be logged too.

### Environment

- Library version: 0.36.1

### PR DESCRIPTION
**Pull request by sombrek**
### Proposed Changes

Closes #205

Scopes of transactions and ad-hoc subprocesses are now shown in the Scope Filter bar when they are active.
The Log now shows when these subprocesses start and finish.

There were no tests for the Show Scopes feature, so I created a basic set.

demo205

### CODE REVIEW

**Comment by sombrek** [comment]
@nikku @barmac FYI

File: lib/features/show-scopes/ShowScopes.js [hunk 1]
```diff
@@ -7,6 +7,10 @@ import {
   clear as domClear
 } from 'min-dom';
 
+import {
+  is
```
Comment (nikku) [inline lib/features/show-scopes/ShowScopes.js:11]: Very confusing that we use `is` instead of the core bpmn-js provided `isAny` ([ref](https://github.com/bpmn-io/bpmn-js/blob/c3ab26b1ab8e33f238cec6c9704f875e4ddc1a1a/lib/util/ModelUtil.js#L33)).

Comment (nikku) [reply lib/features/show-scopes/ShowScopes.js:11]: Let us already use `import { isAny } from 'bpmn-js/lib/util/ModelUtil'` here, cf. https://github.com/bpmn-io/bpmn-js-token-simulation/pull/212

Comment (sombrek) [reply lib/features/show-scopes/ShowScopes.js]: Thanks. Fixed it.

**Review by nikku — APPROVED** [review]
Marvelous :star:
