### PR TITLE
fix: consider link events before inclusive joins

### LINKED ISSUE #153: Inclusive gateway doesn't wait for tokens which are placed before a link catch event
### Describe the Bug

https://github.com/bpmn-io/bpmn-js-token-simulation/assets/28307541/04e587bd-dc11-41d2-a9ae-f6bd64328b9d

Inclusive gateway doesn't wait for tokens which are placed before a link catch event.

### Steps to Reproduce

Run simulation on this diagram:

[diagram (2).bpmn.txt](https://github.com/bpmn-io/bpmn-js-token-simulation/files/14064775/diagram.2.bpmn.txt)

### Expected Behavior

It should wait for the token

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

### PR DESCRIPTION
**Pull request by sombrek**
Closes #153

### Proposed Changes

Joining inclusive gateways now wait for tokens that are placed before a link catch event.

link-catch-demo

### CODE REVIEW

File: lib/simulator/behaviors/InclusiveGatewayBehavior.js [hunk 1]
```diff
@@ -174,21 +184,41 @@ InclusiveGatewayBehavior.prototype._canReachAnyElement = function(elements, curr
   }
 
   if (isSequenceFlow(currentElement)) {
-    return this._canReachAnyElement(elements, currentElement.source, traversed);
+    return this._canReachAnyElement(context, elements, currentElement.source, traversed);
+  }
+
+  if (isLinkCatch(currentElement)) {
+    const sourceName = getLinkName(currentElement);
+    const siblingElements = getChildren(context.scope.parent.element, this._elementRegistry);
```
Comment (nikku) [inline lib/simulator/behaviors/InclusiveGatewayBehavior.js:192]: I'm not sure if we need to summon `getChildren` here, when we can rely on the model instead:

```
currentElement.parent.children
```

should give you exactly what you need.

Comment (nikku) [reply lib/simulator/behaviors/InclusiveGatewayBehavior.js]: Simplified via https://github.com/bpmn-io/bpmn-js-token-simulation/pull/221/commits/59e8d4b94005f5e422a7ca49310ecc36b5cf005c.

**Comment by nikku** [comment]
As always, great contribution, great test coverage :clap:

File: lib/simulator/behaviors/InclusiveGatewayBehavior.js (hunk 1 above)
Comment (sombrek) [reply lib/simulator/behaviors/InclusiveGatewayBehavior.js]: Cool find. Thanks.
